### ISSUE TITLE
useragent

### ISSUE THREAD

**Issue by moh1122** [WillBishop/MiniWeb#1]
Hello
This is an awesome project
Can we use useragent in your proj?

**Comment by WillBishop** [comment]
Do you mean setting a custom user-agent?

I’ve just committed 086a2e1 which added a `var userAgent: String? = nil` to the `InterfaceController.swift` file.

It’s ‘nil’ by default (meaning your user-agent will be automatic), but changing `nil` to a string will use that string as the user-agent.

**Comment by WillBishop** [comment]
Do you mean setting a custom user-agent?

I’ve just committed a6feb7461e63362ea3f655c1bf3b735cb0d8361f which added a `var userAgent: String? = nil` to the `InterfaceController.swift` file.

It’s `nil` by default (meaning your user-agent will be automatic), but changing `nil` to a string will use that string as the user-agent.

**Comment by moh1122** [comment]
thank you @WillBishop for your quick reply yes i mean user-agent i got you i added a string to userAgent variable but the new release "update" is crashing at startup

**Comment by WillBishop** [comment]
The new release of MiniWeb?

**Comment by WillBishop** [comment]
Fixed in 2b859844da7c90faf0f1bbecefb4b855bf0e98fa

**Comment by moh1122** [comment]
Hello @WillBishop 
in you last update userAgent variable is removed, how can we add a user-agent now?
