### ISSUE TITLE
Any webpage not loading

### ISSUE THREAD

**Issue by moh1122** [WillBishop/MiniWeb#3]
Thank you dear for your last commit its running now but the web pages local and other sites are not presented check the screenshot thank you
![simulator screen shot - apple watch series 4 - 44mm - 2018-11-28 at 12 02 54](https://user-images.githubusercontent.com/13592736/49144489-31767400-f306-11e8-8994-263f94065870.png)

**Comment by WillBishop** [comment]
Sorry, I don’t mean to be rude, but are you experienced with Swift?

MiniWeb is not intended for consumers at this stage, it’s intended to be used within other projects.

Your last two ‘issues’ (including this one) were trivial issues.

Nonetheless, I’ve pushed a fix to this issue.
